print("Введите 3 числа")
a = float(input("Введите первое число (a): "))
b = float(input("Введите второе число (b): "))
c = float(input("Введите третье число (c): "))
f = (a*b)+(a*c)
print(f"(a*b)+(a*c)={f}")
